---
title: "LS 빅데이터 스쿨 HW7"
author : "지윤"
date : "2024-09-03"
categories : [bigdata]
jupyter: python3
---
이삭쌤 교재 p37,38

- Scipy 함수 이름
-> pmf : 확률질량함수
-> pdf : 확률밀도함수
-> cdf : 누적분포함수
-> ppf : 퀀타일 함수
-> rvs : 랜덤심플함수

### 기본코드
```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, chi2
```


# ADP 표본점수
> 2022년에 실시된 ADP실기 시험의 통계파트 표준점수는 평균이 30, 표준편차가 5인 정규분포를 따른다고 한다.

### 1) 
ADP실기 시험의 통계파트 표준점수의 밀도함수를 그려보세요.

```{python}
#pdf : 확률밀도함수
x = np.linspace(10, 50, 200)
y = norm.pdf(x, loc = 30, scale = 5)

plt.plot(x, y, color="#f2c94c")

plt.show()
plt.clf() 
```

### 2) 
ADP수험생을 임의로 1명을 선택하여 통계점수를 조회했을 때 45점보다 높은 점수를 받았을 확률을 구하세요.

```{python}
#cdf : 누적분포함수
1-norm.cdf(45, loc = 30, scale = 5)
```

### 3) 
슬통이는 상위10%에 해당하는 점수를 얻었다고 한다면, 슬통이의 점수는 얼마인지 계산해보세요.

```{python}
#pdf : 확률밀도함수
norm.ppf(0.9, loc = 30, scale = 5)
```

### 4) 
슬기로운 통계 생활의 해당 회차 수강생은 16명이었다고 한다. 16명의 통계파트 점수를 평균 내었을때, 이 평균값이 따르는 분포의 확률밀도함수를 1번의 그래프와 겹쳐 그려 보세요.

```{python}
#pdf : 확률밀도함수
#1번 함수 
x = np.linspace(10, 50, 200)
y = norm.pdf(x, loc = 30, scale = 5)
plt.plot(x, y, color="#66b366")

#4번 함수
y2 = norm.pdf(x, loc = 30, scale = 5/np.sqrt(16))
plt.plot(x, y2, color="#99ccff")

plt.show()
plt.clf() 
```

### 5) 
슬기로운 통계생활 ADP반 수강생들의 통계점수를 평균 내었다고할 때,이 값이 38점보다 높게 나올 확률을 구하세요.

```{python}
#cdf : 누적분포함수
1-norm.cdf(38, loc = 30, scale=5/np.sqrt(16))
```


# Covid 19 발병률

> Covid‑19의 발병률은 1%라고 한다.다음은 이번 코로나 사태로 인하여 코로나 의심환자들 1,085
명을 대상으로 슬통 회사의“다잡아”키트를 사용하여 양성반응을 체크한 결과이다.

|  키트/실제 | 양성  | 음성  |
|------------|-------|-------|
|    양성    |  370  |  10   |
|    음성    |  15   |  690  |

### 1) 
다잡아 키트가 코로나 바이러스에 걸린 사람을 양성으로 잡아낼 확률을 계산하세요.

```{python}
#P(키트 양성|실제 양성)
p1 = 370 / (370+15)
p1
```

### 2) 
슬통 회사에서 다잡아 키트를 사용해 양성으로 나온 사람이 실제로는 코로나 바이러스에 걸려있을 확률을 97%라며, 키트의 우수성을 주장했다. 이 주장이 옳지 않은 이유를 서술하세요.

```{python}
#P(실제 양성|키트 양성)
p2 = 370 / (370 +10)
p2 
```

### 3) 
Covid‑19 발병률을 사용하여, 키트의 결과값이 양성으로 나온 사람이 실제로 코로나 바이러스에 걸려있을 확률을 구하세요.

```{python}
#P(실제 양성|키트 양성)
#A = 실제 양성 
#B = 키트 양성
#C = 실제 음성 
#= P(B 교 A) / P(B) 
#= {P(A) * P(B|A)} / {P(A) * P(B|A) + P(C) * P(B|C)}
#P(A) = 0.01 
#P(B|A) (실제가 양성일 때 키트가 양성이 나올 확률) = 370 / (370+15)
#P(C) = 1 - 0.01 = 0.99
#P(B|C) (실제가 음성일 때 키트가 양성이 나올 확률) = 10 / (10+690)
a = 0.01
b_a = p1
c = 1 - a
b_c = 10 / (10+690)

p3 = (a * b_a) / (a * b_a + c * b_c)
p3
```


# 카이제곱 분포와 표본분산

> 자유도가𝑘인 카이제곱분포를 따르는 확률변수𝑋를
과 같이 나타내고,이 확률변수의 확률밀도함수는 다음과 같습니다.

### 1) 
자유도가 4인 카이제곱분포의 확률밀도함수를 그려보세요.

```{python}
#pdf : 확률밀도함수
k = np.linspace(0, 8, 100)
y = chi2.pdf(k, df = 4)
plt.plot(k, y, color = "#e6ccff")
plt.show()
plt.clf()
```

### 2) 
다음의 확률을 구해보세요. 𝑃 (3 ≤ 𝑋 ≤ 5)

```{python}
p = chi2.cdf(5, df=4) - chi2.cdf(3, df=4)
p
```

### 3) 
자유도가 4인 카이제곱분포에서 크기가 1000인 표본을 뽑은 후, 히스토그램을 그려보세요.

```{python}
samples = chi2.rvs(size=1000, df = 4, random_state=20240903)
plt.hist(samples, bins = 30, density=True, color = "#ffcc99")
plt.show()
plt.clf()
```

### 4) 
자유도가 4인 카이제곱분포를 따르는 확률변수에서 나올 수 있는 값 중 상위 5%에 해당하는 값은 얼마인지 계산해보세요.

```{python}
#ppf : 퀀타일 함수
chi2.ppf(0.95, df = 4)
```

### 5) 
3번에서 뽑힌 표본값들 중 상위 5%에 위치한 표본의 값은 얼마인가요?

```{python}
np.percentile(samples, 95)
```


### 6) 
평균이 3, 표준편차가 2인 정규분포를 따르는 확률변수에서 크기가 20인 표본, 𝑥1, …, 𝑥20,을 뽑은 후 표본분산을 계산한 것을 𝑠1^2이라 생각해보죠. 다음을 수행해보세요!

- 같은 방법으로 500개의 𝑠^2들, 𝑠1^2, 𝑠2^2, …, 𝑠500^2 발생시킵니다.
- 발생한 500개의 𝑠^2 들 각각에 4.75를 곱하고, 그것들의 히스토그램을 그려보세요. (히스토그램을 그릴 때 probability = TRUE 옵션을 사용해서 그릴 것)
- 위에서 그린 히스토그램에 자유도가 19인 카이제곱분포 확률밀도함수를 겹쳐그려보세요.

```{python}
np.random.seed(20240903)
n = 20
var = []

for i in range(500):
    x = norm.rvs(loc = 3, scale = 2, size = n)
    var.append(np.var(x, ddof=1))
    
var2 = np.array(var) * 4.75
plt.hist(var2, bins=50, density=True, color="pink")

x = np.linspace(min(var2), max(var2), 100)
y = chi2.pdf(x, df=19)
plt.plot(x, y, linestyle = '--', linewidth=2, color="lightblue")
 
plt.show()
plt.clf()
```